# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('guild_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_id', models.IntegerField(primary_key=True, serialize=False)),
                ('assigment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canvas.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('requirements', models.IntegerField(default=0)),
                ('quest_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=280)),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quest_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canvas.Quest')),
                ('questions', models.ManyToManyField(to='canvas.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('assignment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canvas.Assignment')),
                ('quiz_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canvas.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SkillPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canvas.Question')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canvas.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='guild',
            name='students',
            field=models.ManyToManyField(to='canvas.Student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='quest_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canvas.Quest'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canvas.SkillPoints'),
        ),
    ]
