# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='rubric',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canvas.Quiz'),
        ),
        migrations.AddField(
            model_name='skillpoints',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canvas.Part'),
        ),
    ]
