# Generated by Django 2.0 on 2017-12-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0004_student_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
