# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-11 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0006_assignment_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_admin',
            new_name='is_teacher',
        ),
    ]
