# Generated by Django 2.0 on 2017-12-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0006_assignment_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_admin',
            new_name='is_teacher',
        ),
    ]
