# Generated by Django 2.0 on 2017-12-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0008_auto_20171212_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='numQuestions',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10)], default=5, max_length=2),
        ),
    ]
